// <auto-generated />
using System;
using KlatenUniversityWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KlatenUniversityWebApp.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("KlatenUniversityWebApp.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseID = 1050,
                            Credits = 3,
                            Title = "Chemistry"
                        },
                        new
                        {
                            CourseID = 4022,
                            Credits = 3,
                            Title = "Microeconomics"
                        },
                        new
                        {
                            CourseID = 4041,
                            Credits = 3,
                            Title = "Macroeconomics"
                        },
                        new
                        {
                            CourseID = 1045,
                            Credits = 4,
                            Title = "Calculus"
                        },
                        new
                        {
                            CourseID = 3141,
                            Credits = 4,
                            Title = "Trigonometry"
                        },
                        new
                        {
                            CourseID = 2021,
                            Credits = 3,
                            Title = "Composition"
                        },
                        new
                        {
                            CourseID = 2042,
                            Credits = 4,
                            Title = "Literature"
                        },
                        new
                        {
                            CourseID = 1001,
                            Credits = 3,
                            Title = "Introduction to Computer Science"
                        },
                        new
                        {
                            CourseID = 2001,
                            Credits = 4,
                            Title = "Data Structures"
                        },
                        new
                        {
                            CourseID = 3001,
                            Credits = 3,
                            Title = "Database Systems"
                        });
                });

            modelBuilder.Entity("KlatenUniversityWebApp.Models.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentID")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentID = new Guid("0ced5e71-57c2-414c-9f56-3ab4ce760b6a"),
                            CourseID = 1050,
                            Grade = 0,
                            StudentID = 1
                        },
                        new
                        {
                            EnrollmentID = new Guid("39d02583-0bf8-4899-ac9d-a16fd1b8baed"),
                            CourseID = 4022,
                            Grade = 2,
                            StudentID = 1
                        },
                        new
                        {
                            EnrollmentID = new Guid("45df5326-e0a1-4eee-9e7e-c00e133090ba"),
                            CourseID = 4041,
                            Grade = 1,
                            StudentID = 1
                        },
                        new
                        {
                            EnrollmentID = new Guid("a0bf0403-1829-4927-a878-e765bfe68bab"),
                            CourseID = 1045,
                            Grade = 1,
                            StudentID = 2
                        },
                        new
                        {
                            EnrollmentID = new Guid("e904c09c-53e2-47dc-a56f-68531abdea16"),
                            CourseID = 3141,
                            Grade = 5,
                            StudentID = 2
                        },
                        new
                        {
                            EnrollmentID = new Guid("c57f8e61-e61d-4e86-bae3-ddec23fa2bae"),
                            CourseID = 2021,
                            Grade = 2,
                            StudentID = 2
                        },
                        new
                        {
                            EnrollmentID = new Guid("4ef453fe-f0c7-464a-8f4f-688083b68caa"),
                            CourseID = 1050,
                            StudentID = 3
                        },
                        new
                        {
                            EnrollmentID = new Guid("a85ec596-bf35-4340-a674-35d9d373fd36"),
                            CourseID = 1050,
                            StudentID = 4
                        },
                        new
                        {
                            EnrollmentID = new Guid("9207f636-eac2-430e-82fe-a0a95f3fa23d"),
                            CourseID = 4022,
                            Grade = 5,
                            StudentID = 4
                        },
                        new
                        {
                            EnrollmentID = new Guid("dccf8670-2ddd-4beb-a437-3f5ee915f223"),
                            CourseID = 4041,
                            Grade = 2,
                            StudentID = 5
                        },
                        new
                        {
                            EnrollmentID = new Guid("cf0d4566-9b13-48a5-8059-f40f8250d778"),
                            CourseID = 1045,
                            StudentID = 6
                        },
                        new
                        {
                            EnrollmentID = new Guid("70a8af7f-236a-469e-b143-4f39c373584e"),
                            CourseID = 3141,
                            Grade = 0,
                            StudentID = 7
                        },
                        new
                        {
                            EnrollmentID = new Guid("861fcec0-c015-4ddb-b057-59417e128b69"),
                            CourseID = 1001,
                            Grade = 0,
                            StudentID = 1
                        },
                        new
                        {
                            EnrollmentID = new Guid("9e19d0ce-34a6-438e-9860-11a8cf71b05a"),
                            CourseID = 2001,
                            Grade = 1,
                            StudentID = 1
                        },
                        new
                        {
                            EnrollmentID = new Guid("c34ddae6-0e83-4a21-bb39-6a83557b39b7"),
                            CourseID = 1001,
                            Grade = 1,
                            StudentID = 3
                        },
                        new
                        {
                            EnrollmentID = new Guid("a7a15a0e-c65a-41f3-a9cb-ae4361bb5512"),
                            CourseID = 2001,
                            StudentID = 5
                        },
                        new
                        {
                            EnrollmentID = new Guid("26a7d773-e5a2-4b21-a712-5cc8a0a4891e"),
                            CourseID = 3001,
                            Grade = 0,
                            StudentID = 8
                        });
                });

            modelBuilder.Entity("KlatenUniversityWebApp.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Jl. Sudirman No. 123, Klaten",
                            DateOfBirth = new DateTime(1987, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carson.alexander@klaten.edu",
                            EnrollmentDate = new DateTime(2005, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Major = "Computer Science",
                            Name = "Carson Alexander",
                            PhoneNumber = "081234567890"
                        },
                        new
                        {
                            ID = 2,
                            Address = "Jl. Ahmad Yani No. 45, Klaten",
                            DateOfBirth = new DateTime(1984, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "meredith.alonso@klaten.edu",
                            EnrollmentDate = new DateTime(2002, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Major = "Mathematics",
                            Name = "Meredith Alonso",
                            PhoneNumber = "081234567891"
                        },
                        new
                        {
                            ID = 3,
                            Address = "Jl. Diponegoro No. 67, Klaten",
                            DateOfBirth = new DateTime(1985, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "arturo.anand@klaten.edu",
                            EnrollmentDate = new DateTime(2003, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Major = "Physics",
                            Name = "Arturo Anand",
                            PhoneNumber = "081234567892"
                        },
                        new
                        {
                            ID = 4,
                            Address = "Jl. Gajah Mada No. 89, Klaten",
                            DateOfBirth = new DateTime(1984, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gytis.barzdukas@klaten.edu",
                            EnrollmentDate = new DateTime(2002, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Major = "Chemistry",
                            Name = "Gytis Barzdukas",
                            PhoneNumber = "081234567893"
                        },
                        new
                        {
                            ID = 5,
                            Address = "Jl. Pemuda No. 12, Klaten",
                            DateOfBirth = new DateTime(1984, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yan.li@klaten.edu",
                            EnrollmentDate = new DateTime(2002, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Major = "Engineering",
                            Name = "Yan Li",
                            PhoneNumber = "081234567894"
                        },
                        new
                        {
                            ID = 6,
                            Address = "Jl. Veteran No. 34, Klaten",
                            DateOfBirth = new DateTime(1983, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "peggy.justice@klaten.edu",
                            EnrollmentDate = new DateTime(2001, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Major = "Biology",
                            Name = "Peggy Justice",
                            PhoneNumber = "081234567895"
                        },
                        new
                        {
                            ID = 7,
                            Address = "Jl. Kartini No. 56, Klaten",
                            DateOfBirth = new DateTime(1985, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura.norman@klaten.edu",
                            EnrollmentDate = new DateTime(2003, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Major = "Psychology",
                            Name = "Laura Norman",
                            PhoneNumber = "081234567896"
                        },
                        new
                        {
                            ID = 8,
                            Address = "Jl. Pahlawan No. 78, Klaten",
                            DateOfBirth = new DateTime(1987, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nino.olivetto@klaten.edu",
                            EnrollmentDate = new DateTime(2005, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Major = "Economics",
                            Name = "Nino Olivetto",
                            PhoneNumber = "081234567897"
                        });
                });

            modelBuilder.Entity("KlatenUniversityWebApp.Models.Enrollment", b =>
                {
                    b.HasOne("KlatenUniversityWebApp.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlatenUniversityWebApp.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("KlatenUniversityWebApp.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("KlatenUniversityWebApp.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
